-- MySQL Script generated by MySQL Workbench
-- Sat Feb  4 18:22:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`sectors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sectors` (
  `id` INT NOT NULL,
  `name` VARCHAR(50) NULL,
  `description` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL,
  `name` VARCHAR(50) NULL,
  `email` VARCHAR(50) NULL,
  `available_funds` DOUBLE NULL,
  `blocked_funds` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stocks` (
  `id` INT NOT NULL,
  `name` VARCHAR(20) NULL,
  `total_volume` INT NULL,
  `unallocated` INT NULL,
  `price` DOUBLE NULL,
  `sectors_id` INT NOT NULL,
  PRIMARY KEY (`id`, `sectors_id`),
  INDEX `fk_stocks_sectors1_idx` (`sectors_id` ASC) VISIBLE,
  CONSTRAINT `fk_stocks_sectors1`
    FOREIGN KEY (`sectors_id`)
    REFERENCES `mydb`.`sectors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`holdings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`holdings` (
  `id` INT NOT NULL,
  `volume` INT NULL,
  `bid_price` DOUBLE NULL,
  `bought_on` DATE NULL,
  `users_id` INT NOT NULL,
  `stocks_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`, `stocks_id`),
  INDEX `fk_holdings_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_holdings_stocks1_idx` (`stocks_id` ASC) VISIBLE,
  CONSTRAINT `fk_holdings_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_holdings_stocks1`
    FOREIGN KEY (`stocks_id`)
    REFERENCES `mydb`.`stocks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`market_day`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`market_day` (
  `id` INT NOT NULL,
  `day` INT NULL,
  `status` VARCHAR(10) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `id` INT NOT NULL,
  `bid_price` DOUBLE NULL,
  `type` VARCHAR(4) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `status` VARCHAR(20) NULL,
  `bid_volume` INT NULL,
  `executed_volume` INT NULL,
  `users_id` INT NOT NULL,
  `stocks_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`, `stocks_id`),
  INDEX `fk_orders_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_orders_stocks1_idx` (`stocks_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_stocks1`
    FOREIGN KEY (`stocks_id`)
    REFERENCES `mydb`.`stocks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stocks_has_market_day`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stocks_has_market_day` (
  `stocks_id` INT NOT NULL,
  `market_id` INT NOT NULL,
  `open` DOUBLE NULL,
  `high` DOUBLE NULL,
  `low` DOUBLE NULL,
  `close` DOUBLE NULL,
  `volume` INT NULL,
  PRIMARY KEY (`stocks_id`, `market_id`),
  INDEX `fk_stocks_has_market_day_market_day1_idx` (`market_id` ASC) VISIBLE,
  INDEX `fk_stocks_has_market_day_stocks_idx` (`stocks_id` ASC) VISIBLE,
  CONSTRAINT `fk_stocks_has_market_day_stocks`
    FOREIGN KEY (`stocks_id`)
    REFERENCES `mydb`.`stocks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stocks_has_market_day_market_day1`
    FOREIGN KEY (`market_id`)
    REFERENCES `mydb`.`market_day` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
