"""<msg>

Revision ID: 41e961c69669
Revises: d3dd44b06e22
Create Date: 2023-02-08 20:52:16.047232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e961c69669'
down_revision = 'd3dd44b06e22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
