"""<msg>

Revision ID: 6b5bd58978bb
Revises: 41e961c69669
Create Date: 2023-02-08 21:41:00.900021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b5bd58978bb'
down_revision = '41e961c69669'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
