"""updated users table

Revision ID: a087f3e70045
Revises: ba5c35bf264b
Create Date: 2023-02-07 19:36:04.565775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a087f3e70045'
down_revision = 'ba5c35bf264b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
