"""updated users table

Revision ID: ba5c35bf264b
Revises: c0fdb243e55f
Create Date: 2023-02-07 18:19:28.494979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba5c35bf264b'
down_revision = 'c0fdb243e55f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('token', sa.String(length=40), nullable=True))
    op.add_column('users', sa.Column('loggedIn', sa.Boolean(), nullable=True))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('users', 'loggedIn')
    op.drop_column('users', 'token')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
