"""models

Revision ID: f3ff73d722e5
Revises: 
Create Date: 2023-01-24 23:45:34.943667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3ff73d722e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')+"CASCADE"
    op.drop_table('user')+"CASCADE"   
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')+"CASCADE"
    op.drop_table('user')+"CASCADE"
    # ### end Alembic commands ###
